### ISSUE TITLE
Popover getContents() returns a non-iterable to destructuring assignment

### ISSUE THREAD

**Issue by morungos** [thednp/bootstrap.native#419]
The `getContents()` function in the v4 popover returns an object with keys 0 and 1, and yet it's used in a destructuring assignment to an array, which requires that it's an iterable. My read on the spec is that only iterables are allowed here: https://tc39.es/ecma262/multipage/ecmascript-language-expressions.html#sec-destructuring-assignment. The Babel transpiled code throws a nice clear error:

```
index.js:113 Uncaught TypeError: Invalid attempt to destructure non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at _nonIterableRest (index.js:113)
    at _slicedToArray (index.js:113)
    at new Popover (popover-native.js:16)
```

Chrome dev tools also flags an error on:

```
let [x3, x4] = {0: "x3", 1: "x4"};
VM1053:1 Uncaught TypeError: {(intermediate value)(intermediate value)} is not iterable
    at <anonymous>:1:16
```

Even without transpiling this shows a weirdly unexplainable "TypeError: undefined is not a function" on the return from `getContents()`

This is a simple fix: `getContents()` should return, e.g., an array. 

Note that the v5 component does not include this logic. 

- BSN version is 4.0.3.
- Issue shows at: https://github.com/thednp/bootstrap.native/blob/77f7df071f831a2d0b46157b8ec69bb4fb98f2ae/src/components-v4/popover-native.js#L64 and also https://github.com/thednp/bootstrap.native/blob/77f7df071f831a2d0b46157b8ec69bb4fb98f2ae/src/components-v4/popover-native.js#L257
- To reproduce, build with Babel (I used 7.8.3) but to be honest, the issue shows fine on inspecting the code

I know the vanilla builds worked, but they appear to have used a simpler transpiling system which worked around the issue.

**Comment by thednp** [comment]
Thanks for dropping by.

I cannot have a look right now, but please feel free to propose your best solution, I will check ASAP, perhaps today.

**Comment by morungos** [comment]
Done, and many thanks -- this is a lifesaving package, and has enabled me to dispense with a ton of unnecessary junk.

**Comment by thednp** [comment]
We can close this now. Cheers :)
