### ISSUE TITLE
Bootstrap v5 backdrop over offcanvas

### ISSUE THREAD

**Issue by KenHaggerty** [thednp/bootstrap.native#422]
The bootstrap-native.js v4.0.4 does not implement the offcanvas-backdrop class. The offcanvas-backdrop class has z-index = 1040. The offcanvas class has z-index = 1045.  The BSN Offcanvas component is using the modal-backdrop class which has z-index = 1050.

**Comment by thednp** [comment]
Yes, it's a way we found to optimize things. What's the problem?

**Comment by KenHaggerty** [comment]
![offcanvas-overlay](https://user-images.githubusercontent.com/26002116/130517464-15b06776-73fa-42e1-9bf7-ef35c301c456.png)

**Comment by thednp** [comment]
Hm might be a change in the CSS of the latest original stable Bootstrap CSS.

Will investigate and provide a fix asap.

**Comment by thednp** [comment]
Is there a possibility this is caused by some markup error? Do you have a link to a demo we can have a look?

The current latest Bootstrap is still 5.0.2 and cannot find a way to replicate that issue.

**Comment by KenHaggerty** [comment]
I am using Bootstrap v5.1.0. [Bootstrap Versions](https://getbootstrap.com/docs/versions/)

**Comment by thednp** [comment]
Thanks for reporting, update incoming.

**Comment by thednp** [comment]
@KenHaggerty please latest master. Thanks

**Comment by KenHaggerty** [comment]
Latest master works for me on Bootstrap v5.1.0 but the offcanvas-backdrop class does not exist in Bootstrap v5.0.2. In v5.0.2 the overlay dismisses but is not shaded.

**Comment by thednp** [comment]
We can't make it work with all 5.x versions, we either make it work with latest 5.1 or not.

**Comment by KenHaggerty** [comment]
I bet these changes support Offcanvas in navbars and under modals. I am in the process of updating my sites to Bootstrap v5.1. You can close the issue.
